// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsoN4bCdkspjbDj7cpfniA-G8QYeMcVTc',
    appId: '1:987373725314:web:bbe59a9e8706f511d9f69b',
    messagingSenderId: '987373725314',
    projectId: 'ecommerce-665da',
    authDomain: 'ecommerce-665da.firebaseapp.com',
    storageBucket: 'ecommerce-665da.appspot.com',
    measurementId: 'G-8Y11S2SCBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY-WryePzbyqxLB7PDY_25P17fhV6C4FU',
    appId: '1:987373725314:android:9fe7933b87f651ced9f69b',
    messagingSenderId: '987373725314',
    projectId: 'ecommerce-665da',
    storageBucket: 'ecommerce-665da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPGPHMEH2Jarg5DHqoUaJL0WswrzPC_sA',
    appId: '1:987373725314:ios:3978b0ef74b9a185d9f69b',
    messagingSenderId: '987373725314',
    projectId: 'ecommerce-665da',
    storageBucket: 'ecommerce-665da.appspot.com',
    iosClientId: '987373725314-ooag8tsn57qe4kdb6omd5814eomgp090.apps.googleusercontent.com',
    iosBundleId: 'com.example.emall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPGPHMEH2Jarg5DHqoUaJL0WswrzPC_sA',
    appId: '1:987373725314:ios:3978b0ef74b9a185d9f69b',
    messagingSenderId: '987373725314',
    projectId: 'ecommerce-665da',
    storageBucket: 'ecommerce-665da.appspot.com',
    iosClientId: '987373725314-ooag8tsn57qe4kdb6omd5814eomgp090.apps.googleusercontent.com',
    iosBundleId: 'com.example.emall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsoN4bCdkspjbDj7cpfniA-G8QYeMcVTc',
    appId: '1:987373725314:web:298f4ab6c68001e9d9f69b',
    messagingSenderId: '987373725314',
    projectId: 'ecommerce-665da',
    authDomain: 'ecommerce-665da.firebaseapp.com',
    storageBucket: 'ecommerce-665da.appspot.com',
    measurementId: 'G-0KKBTTBWJL',
  );
}
